### ISSUE TITLE
[Suggestions] February Suggestions

### ISSUE THREAD

**Issue by quasixi** [quasixi/RPG-Maker-MV#6]
_Every month I will open a discussion where you may recommend plugins, addons, apps, or tutorials that you want me to create. This discussion will be closed in the middle of the month. A poll will be created for the second half of the month filled with approved requests. At the end of the month I will pick the top 1 or more requests and create them in the following month._

**Requests Submission deadline:** February 20, 2016 around noon.

Feel free to request anything. Anything that I think can be created under a month will be approved.

_* If you are a Patreon supporter of Rank 2 or higher, send me a message on Patreon with your github user name so I can confirm who you are._

**Comment by matthew30903** [comment]
What about a rouge-like movement system? Specified enemies move on a turn based system. The ideas is to be able to make puzzles like in the SNES game Lufia II.

A little bit more in depth would be to be able to run events on each of these "turns" as well. Like say we want the player to clear out the room of plants, but they grow back every three moves.

Another idea, I bet a more complex one, is a random dungeon generator. There is one for MV, but it is a little simplistic for games that wish to have puzzles within them. Something that allows you to use rebuilt rooms as a tileset and have events randomly placed as well, though that could be made using other plugins that spawn events.  A system similar to Kai Monkey's Random Dungeons for Ace. The ability to set custom parameters to each floor of the dungeon and each room such as: How many time a said room will appear, what directions do other rooms connect to it (So rooms with only one opening would not get places where they could not get accessed), and if a room must be generated before the exit chamber. Of course this is a large one and might be better as a commission.

Thank you for all of your heard work.

**Comment by quasixi** [comment]
**rouge-like movement system**
I just looked at some Lufia II gameplay. Do you mean like those switches, weight switches, push, pull, grab, shotting arrows to hit switches, ect. ? I'm not sure what you mean by the "enemies move on a turn based system" though.

**random dungeon generator**
Concept seems easy, but not sure about implementing into MV. I would have to do a few "attempts" to see how much work that would be in MV.

Both sound like awesome ideas though! Thanks for the suggestions!

**Comment by matthew30903** [comment]
The switches, push, pull, etc... would be extremely cool, but what I am talking about is how enemies (In this case events) only move when the player does. Say each enemy moves in a pattern unless the player gets too close, a on map encounter system. The enemies would be using this move rout (I use Yanfly's Event Chase Player and Orange Move Character To), it gets disrupted if the player gets within the event's line of sight running or attacking the player. With the system that I was describing, the event would not move on its path unless the player moves. 

This allows for puzzles where the player might not want to attack the enemy. Say an event moves two grid places (Or whatever movement system the game uses) per space the player moves. The player will need to think how to move so the event does not see them, but steps on a switch that opens a door and stays on it. It the event sees the player, it will quickly catch up with them and the player will have to kill it, thus not having a way to get past the puzzle. This give depth to enemy behavior and puzzles in and of itself.

**Comment by quasixi** [comment]
Ah I didn't notice that lol.

I'll approve of that idea. I have an idea on how to create it and keeping it compatible with most plugins.

**Comment by carlogemmani** [comment]
Hi Quasi! 
- As I was telling you in the message it would be great to have some videotutorials with voice explanation to explain how to use the plugins. So that we can be guided into making a game using them. Having the bits and pieces and the other videos makes it a bit daunting to pick up. This is probably because I don't know much about programming. So that would be awesome.
- The other thing would be an official release of the plugins, especially the ABS one.
 
Amazing works! Thank you! I have been waiting for this for quite a bit! :dancer: 

Carlo

**Comment by quasixi** [comment]
Hey Carlo!

Tutorials on my plugins will most likely be won by default, since I've been having a few people ask for them. Though I'm unsure if I'll do video + voice over. Since that's a bit of extra work. I might try to see if I can find someone to help create the videos.
- I should probably mention that tutorials and plugins will have a separate poll. Since I want to be able to create at least 1 tutorial and 1 plugin a month.

Besides the ABS, which other plugins need an official release? I planning on releasing the ABS and Sprite before the end of this month, hopefully!

**Comment by carlogemmani** [comment]
Hi Quasi!
Well if the **input plugin** is not out yet, that's a good one (but Maybe I just need to look somewhere that I missed :P). hmmm I guess it would be awesome to have one where you can change the sprite depending on what armor or weapon skin you are using, which would also do miracles for character creation and customization. But honestly this one would not be of any priority, it's just something I would like to see the light of day sometime in the future. 
  I was also wandering if it was possible to insert variables into the ABS parameter; for example  skill cooldowns, it would be cool to insert a formula there with a basic number of frames that can be reduced by an Agility scaled modifier. So that if the player agility gets higher the cooldown for the powers reduces. That way by adding a variable there it would be a world of freedom into gameplay mechanics. 
:) I am reading through the documentation for movement. Looks fantastic.

thank you!

Carlo

**Comment by quasixi** [comment]
Input plugin's been out for a few months now!
http://forums.rpgmakerweb.com/index.php?/topic/51087-quasi-input/
or
http://quasixi.com/quasi-input/

As for abs suggestions, you can add them into this issue, ( or post at the thread in RMW ):
https://github.com/quasixi/RPG-Maker-MV/issues/7

or create your own, just add something like
**[ABS Suggestions]**
in the title

**Comment by Roguedeus** [comment]
Would you be up to creating an advanced Item Scene? Similar to Bubbles TMI Scene for VXAce?
https://mrbubblewand.wordpress.com/rgss3/too-much-information-item-scene/

The only compatibility consideration I can think of would be Yanfly's Item Upgrade Slots. Which already changes the scene slightly.

Thanks for your time! :)

**Comment by quasixi** [comment]
Yup that would be fine!

**Comment by bigorados** [comment]
Would it be possible to make a plugin that let's you edit the sprites of the sideview battlers, to make you choose from any size, to as many frames, and as many animations you could make, and being able to costumize them step by step?
btw, sorry for posting on you patreon page >_>

**Comment by quasixi** [comment]
Sure, I could pretty much just use my sprite animation app for that and make a plugin that makes the side view battlers read my sprite json instead.
Though I'm unsure what you mean by "being able to costumize their actions step by step"

**Comment by bigorados** [comment]
For example,in the default SV sprite sheet we are bound to at max being able to choose which animation will be played when, by editing the row and the column of the spritesheet, and we can't give any real instructions on how we want to, for example, the "attack" skill animation to look, say I have a claw character, and i'm (as a pixel artist) made animations for him, then when i get him to rpg maker i want that when I select attack, he runs toward the target and do a double slice with his claws, and say that these animations have maybe 8 frames for the running cycle, and 6 frames for the attack itself, and that the animations for him would fit in a 380x380 grid for each frame (the size of the sprite).
Ohter thing that i didn't mention that would be very important would be to also set up the enemy (SV of course) and be able to set their reactions, literally customize actions step by step would be dictate how the character will animate when you select "X" action, so when the sv enemy get hit he reacts to the attack and play a hitstun animation.
What i mean by enemy reaction apply also for, say for example i have made a upwards slash for a sowrdsman and i want to the animation to launch the enemy in the air when it hits the enemy, any kind of reaction really, ground bounces, maybe a grab reaction, say your character grabs the enemy and run arround with him in screen (maybe a way to do this would be actor grabs animation > enemy being grabbed animation > set the actor to go to X,Y using "running grab" animation > set enemy to X,Y using "being grabbed" animation).
I'm asking basically for a system that you can make those flashy combo battles =V

**Comment by carlogemmani** [comment]
Yeah this one above would be cool. 

> I'm asking basically for a system that you can make those flashy combo battles =V

https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSczhoBX_2cbfOT5D_mGdFt4cB8t_hfu9o60SVJzPXdFD-UW2Ea
https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSczhoBX_2cbfOT5D_mGdFt4cB8t_hfu9o60SVJzPXdFD-UW2Ea
I am interested as well, being an animator. I wouldn't mind doing something like this in the picture without being bound by the 3X3. Just put them all in line, and then give every stripe its own action button. Say press 1 and does the attack animation. 2 does the jump animation. So the animation would play the entire row of action. 

On this note, it would be cool to be able to customize the animation of monsters attacks, skills, death, and movement. As well as the skills itself, instead of being animated in the skill animation could be evented:D

I love the freedom of sprite size of RPG MV, but the animation is still tricky to do

thank you Quasi!
(still though, the ABS fixes would have priority in my opinion, just throwing down ideas.)
And the full on isometric graphics? that's awesome. :+1: You have my help if you need it 

cheers!

Carlo

**Comment by quasixi** [comment]
@bigorados Well that part seems very similar to Yanfly's Action Sequences ( motions are in pack 2 ). So I can approve extended my sprite plugin for sideview battlers, but a full sequence motion is a bit much. I probably spent like 70-80% of my time working on my ABS to make the skill sequences lol. Though if the SV Sprite extension, does get picked for March ( or just gets made anyways ) You can also add the sequence to March's suggestions, since I feel like it's more of a 1-2 month thing.

@carlogemmani Pretty much same as above =p

**Comment by bigorados** [comment]
I see, then you already know my March request =3

**Comment by quasixi** [comment]
Closing day. Poll will be up shortly.

**Comment by matthew30903** [comment]
For the July poll I would like to bring back up the dungeon generator idea. There is currently none that are stable or customizable enough to be useful and I could see most games finding one useful. I would be using the one that Kai Monkey's from VX Ace as an example.

If that is too much for a month's time, a plugin that give more item categories in the menu using either notetags or an external file for keeping track of what items are in what category would be great. Though Yanfly comparability with both the menu seen and the instanced items would be needed for most people. I do not know how hard that would be.

Thank you for all your hard work.

**Comment by Cats777** [comment]
All I really want is party AI for QuasiABS.

**Comment by quasixi** [comment]
Ops sorry guys my patreon post was linking to the wrong issue. The place for July is here:
https://github.com/quasixi/Quasi-MV-Master-Demo/issues/3

I copied over your suggestions and added my reply to them there.
